#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-gtools
Version  : 3.5.0
Release  : 15
URL      : http://cran.r-project.org/src/contrib/gtools_3.5.0.tar.gz
Source0  : http://cran.r-project.org/src/contrib/gtools_3.5.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n gtools

%build

%install
rm -rf %{buildroot}
export LANG=C
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library gtools
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library gtools


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/gtools/ChangeLog
/usr/lib64/R/library/gtools/DESCRIPTION
/usr/lib64/R/library/gtools/INDEX
/usr/lib64/R/library/gtools/Meta/Rd.rds
/usr/lib64/R/library/gtools/Meta/data.rds
/usr/lib64/R/library/gtools/Meta/hsearch.rds
/usr/lib64/R/library/gtools/Meta/links.rds
/usr/lib64/R/library/gtools/Meta/nsInfo.rds
/usr/lib64/R/library/gtools/Meta/package.rds
/usr/lib64/R/library/gtools/NAMESPACE
/usr/lib64/R/library/gtools/NEWS
/usr/lib64/R/library/gtools/R/gtools
/usr/lib64/R/library/gtools/R/gtools.rdb
/usr/lib64/R/library/gtools/R/gtools.rdx
/usr/lib64/R/library/gtools/data/ELISA.rda
/usr/lib64/R/library/gtools/help/AnIndex
/usr/lib64/R/library/gtools/help/aliases.rds
/usr/lib64/R/library/gtools/help/gtools.rdb
/usr/lib64/R/library/gtools/help/gtools.rdx
/usr/lib64/R/library/gtools/help/paths.rds
/usr/lib64/R/library/gtools/html/00Index.html
/usr/lib64/R/library/gtools/html/R.css
/usr/lib64/R/library/gtools/libs/gtools.so
/usr/lib64/R/library/gtools/libs/symbols.rds
